### ISSUE TITLE
Build errors on macOS

### ISSUE THREAD

**Issue by kakysha** [ZipCPU/vgasim#3]
1. First of all, on macOS you have to explicitly tell clang than you using c++11 dialect, by adding flag `-std=c++11`

    I tried doing it properly using Make `$(FLAGS)`, but you overwrite them in your SUBMAKES, so I ended up adding `echo " -std=c++11"` at the end of `bench/cpp/vversion.sh`, a hack for sure.

2. After that some compilers error start to pop, but they are fixable, PR #2 

3. And the last incompatibility macOS thing, is that default macos `tar` does not support `--transform` flag, so I ended up installing `brew install gnu-tar` and replacing `tar` command in `bench/cpp/Makefile` to `gtar`.

After that the testbench finally built and worked on latest macOS Catalina.

**Comment by ZipCPU** [comment]
Hmm ... let's see.  A better fix for 3) would be to remove "archive" from a target in bench/cpp/Makefile.

PR #2 looks good to me.

Can you explain your 1) above to me?  The SUBMAKE command is just a notational convenience, and could be updated if necessary.

Dan

**Comment by ZipCPU** [comment]
Two more questions: 1) Why is `-std=c++11` needed?  Is there a C++ feature that's only supported in `c++11` and not in later versions?  and 2) why not adjust the $(CFLAGS) variable within the Makefile in `bench/cpp`?

**Comment by kakysha** [comment]
C++11 needed for:
`glibmm/ustring.h:1092:18: error: expected ';' at end of declaration list
  ~FormatStream() noexcept;` and 20+ similar errors about specifiers (`noexcept`) introduced by C++11 standard.
Of course it is supported by later versions, but seems like clang installed by XCode (latest possible version, `Apple clang version 11.0.3 (clang-1103.0.32.59)`) is using C99 by default.

I was afraid of modifying nested Makefiles, as idk in how many of them should I propagate that flag. You probably know it better, so pick the most suitable way of adding it.

**Comment by ZipCPU** [comment]
Ahh ... the dependency is within glibmm.  Thanks!

Fixed in [2741523](https://github.com/ZipCPU/vgasim/commit/274152357afc2cc4ae08722bf743778fc554a550).

Dan
