### ISSUE TITLE
Make file failing on Ubuntu  22.04.2 LTS WSL

### ISSUE THREAD

**Issue by devinatkin** [ZipCPU/vgasim#7]
I'm having issues running the make file in this context 

vgasim.h:41:10: fatal error: gtkmm.h: No such file or directory
   41 | #include <gtkmm.h>
      |          ^~~~~~~~~

My guess is that there's something missing in the make

**Comment by ZipCPU** [comment]
The C++ simulation models depend heavily upon the GTK++ library.  It looks like you don't have it installed.

Have you tried `sudo apt install libgtkmm-3.0-dev`?

**Comment by ZipCPU** [comment]
Closed for a lack of comment.
