### ISSUE TITLE
Unable to build due to warnings

### ISSUE THREAD

**Issue by Tiebe** [ZipCPU/vgasim#9]
```
make[1]: Nothing to be done for 'all'.
verilator -Wall --MMD -O3 --trace -y ../../rtl -cc demo.v
%Warning-GENUNNAMED: memdev.v:79:2: Unnamed generate block 'genblk2' (IEEE 1800-2017 27.6)
                                  : ... Suggest assign a label with 'begin : gen_<label_name>'
   79 |  begin
      |  ^~~~~
                     demo.v:68:1: ... note: In file included from 'demo.v'
                     ... For warning description see https://verilator.org/warn/GENUNNAMED?v=5.020
                     ... Use "/* verilator lint_off GENUNNAMED */" and lint_on around source to disable this message.
%Warning-GENUNNAMED: memdev.v:87:11: Unnamed generate block 'genblk2' (IEEE 1800-2017 27.6)
                                   : ... Suggest assign a label with 'begin : gen_<label_name>'
   87 |  end else begin
      |           ^~~~~
                     demo.v:68:1: ... note: In file included from 'demo.v'
%Error: Exiting due to 2 warning(s)
make[1]: *** [Makefile:68: obj_dir/Vdemo.mk] Error 1
make[1]: *** Deleting file 'obj_dir/Vdemo.mk'
make: *** [Makefile:49: demo] Error 2
```

**Comment by ZipCPU** [comment]
Yeah ... Verilator's "lint" got upgraded over the years.  I've got fixes for these issues, so let me push them this week.

**Comment by fetohiaras** [comment]
If anyone's running into the same issue, I have found a temporary solution to it: I've opened the main Makefile, went into the other makefiles listed under SUBMAKE, and added the flag -Wno-GENUNNAMED to the VFLAGS parameter on each one of them (and the FLAGS parameter in the /bench/cpp makefile just to be sure), and it compiled. 

![Captura de tela de 2024-07-19 20-12-37](https://github.com/user-attachments/assets/171181c4-46bb-4e8c-84e3-95eed3a591b4)

Seems to work fine now, despite the ignored warnings.

**Comment by ZipCPU** [comment]
This issue should now be fixed.  I've merged the development branch into the master, and then also merged the updates from the [wb2axip](https://github.com/ZipCPU/wb2axip) project into here.  I've also verified that all of the simulations (there are now more of them) are working.  Not all of the proofs are passing at present, so that will take some work to deal with still.  You should find that these updates fix your issues.

**Comment by Tiebe** [comment]
Awesome, thanks!
